<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="Avalonia.Fonts.Inter" />
    <PackageReference Include="Avalonia.Diagnostics" Condition="'$(Configuration)' == 'Debug'" />
    <PackageReference Include="Material.Icons.Avalonia" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <!-- Pinned to patched version for https://github.com/tmds/Tmds.DBus/security/advisories/GHSA-xrw6-gwf8-vvr9 -->
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DotLuxafor\DotLuxafor.csproj" />
  </ItemGroup>

</Project>
